### ISSUE TITLE
Missing Clash and Maverick

### ISSUE THREAD

**Issue by JoeCourtneyW** [JoeCourtneyW/R6J#2]
Need to add new operators from Grim Sky.
Clash: 
- Badge URL: assets/images/badge-clash.133f243da38661bf.png
- Index: 3:10
- Gadget ID: sloweddown
- Gadget Stat Name: Enemies Slowed With CCE Shield
- Category: DEF

Maverick: 
- Badge URL: assets/images/badge-maverick.7eab7c75e7aaecb3.png
- Index: 2:10
- Gadget ID: wallbreached
- Gadget Stat Name: Walls Breached Using Blowtorch
- Category: ATK

**Comment by Banana007** [comment]
Hello,
When comes the 2 Operators ?
