### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by Banana007** [JoeCourtneyW/R6J#4]
Hello, 
When comes the Update with the new Operatores ?.

Missing:

Maverick
Kaid
Nomad
Clash

**Comment by KoneyMC** [comment]
Yes that would be pretty cool! Is there anything else to come or is it not developed any further?

**Comment by JoeCourtneyW** [comment]
I will update the project to reflect new operators and updates made in the past few months.

Expect an update to be pushed within the next week.

**Comment by KoneyMC** [comment]
btw it may be that the R6Player#getRank() method does not work correctly because every player is shown as unraked even though he is ranked.

**Comment by JoeCourtneyW** [comment]
> btw it may be that the R6Player#getRank() method does not work correctly because every player is shown as unraked even though he is ranked.

I've tested this and haven't been able to recreate it. If you continue to have issues with this, create another issue
