### ISSUE TITLE
Maven does not work

### ISSUE THREAD

**Issue by FrankHeijden** [JoeCourtneyW/R6J#6]
Repo: http://jcenter.bintray.com

**Comment by FrankHeijden** [comment]
Sorry, please update maven repo to 1.0.4 & snapshot build

**Comment by JoeCourtneyW** [comment]
Apologies, I forgot to release 1.0.4 on maven. It should be there now

**Comment by FrankHeijden** [comment]
What's the official repo? jcenter doesn't have it updated yet.

**Comment by JoeCourtneyW** [comment]
Nexus/Sonatype is the official repo
