### ISSUE TITLE
R6Player#getBulletsFired()

### ISSUE THREAD

**Issue by FrankHeijden** [JoeCourtneyW/R6J#9]
R6Player#getBulletsFired() method returns sometimes 0;
R6Player#getRank() does not return the correct rank;
R6Player#getXp() does not return the total XPcount

**Comment by JoeCourtneyW** [comment]
Please provide proof that getRank() and getXp() do not work. From my testing they are returning correct values. getBulletsFired() is broken on Ubisoft's side and there is nothing I can do to fix it.

**Comment by FrankHeijden** [comment]
Rank#getDisplayName() & Rank#getIconUrl() returns:
<img width="226" alt="Screenshot 2019-03-19 at 18 19 50" src="https://user-images.githubusercontent.com/22407829/54627635-204ba180-4a74-11e9-9f4d-f8d1b407ba87.png">

while it should be:
<img width="1207" alt="Screenshot 2019-03-19 at 18 19 23" src="https://user-images.githubusercontent.com/22407829/54627665-2f325400-4a74-11e9-9fdd-93a9204acf9d.png">

R6Player#getXp() returns:
<img width="94" alt="Screenshot 2019-03-19 at 18 24 58" src="https://user-images.githubusercontent.com/22407829/54627756-58eb7b00-4a74-11e9-9d5f-9ba88f9ff645.png">

while it should be:
<img width="192" alt="Screenshot 2019-03-19 at 18 25 56" src="https://user-images.githubusercontent.com/22407829/54627811-76204980-4a74-11e9-82e6-7d7a08313da2.png">

Tested with UPLAY account SparkyPotato.NB and the website https://r6.tracker.network/profile/pc/SparkyPotato.NB.

**Comment by JoeCourtneyW** [comment]
R6Player#getXp() is not designed to return total xp. I could change that but that is not my first priority currently. Can you please show me your code for loading the player and getting their rank though so I can better see what's causing the issue.

**Comment by FrankHeijden** [comment]
Can you create a new variable for the total XP then?

```
this.api = new R6J(new Auth("email", "password"));
R6Player r6player = api.getPlayerByName("SparkyPotato.NB", Platform.UPLAY);
System.out.println("Rank name: " + r6player.getRank().getDisplayName());
System.out.println("Rank icon url: " + r6player.getRank().getIconUrl());
```
output:
Rank name: Unranked
Rank icon url: https://i.imgur.com/sB11BIz.png

**Comment by JoeCourtneyW** [comment]
You didn't change your region to EU and ASIA. You NA Rank is Unranked. Closing this and opening another issue for totalXp()
